#used for tests

pushword:
  apps:
    - {
        hosts: ["localhost.dev", "localhost"],
        base_url: "https://localhost.dev",
        randomTest: 123,
        admin_block_editor: false,
        admin_block_editor_disable_listener: true,
      }
    - {
        hosts: [pushword.piedweb.com],
        base_url: "https://pushword.piedweb.com",
        flat_content_dir: "%kernel.project_dir%/../docs/content",
        static_dir: "%kernel.project_dir%/../../docs",
        name: "Pushword",
        favicon_path: "/assets/favicons/",
        static_generators:
          [
            Pushword\StaticGenerator\Generator\PagesGenerator,
            Pushword\StaticGenerator\Generator\RobotsGenerator,
            Pushword\StaticGenerator\Generator\ErrorPageGenerator,
            Pushword\StaticGenerator\Generator\CopierGenerator,
            Pushword\StaticGenerator\Generator\CNAMEGenerator,
          ],
        assets:
          { javascripts: ["/assets/app.js"], stylesheets: ["/assets/tw.css"] },
        color_bg: "#fff",
        static_copy: ["assets"],
      }
