#used for tests

pushword:
  apps:
    - {
        hosts: ["localhost.dev", "localhost"],
        base_url: "https://localhost.dev",
        randomTest: 123,
        generated_og_image: true,
        admin_block_editor: false,
        admin_block_editor_disable_listener: true,
        locales: "fr|en",
        page_update_notification_from: test@example.tld,
        page_update_notification_to: test@example.tld,
      }
    - {
        hosts: [pushword.piedweb.com],
        base_url: "https://pushword.piedweb.com",
        flat_content_dir: "%kernel.project_dir%/../docs/content",
        static_dir: "%kernel.project_dir%/../../docs",
        name: "Pushword",
        favicon_path: "/assets/favicons/",
        static_generators:
          [
            Pushword\StaticGenerator\Generator\PagesGenerator,
            Pushword\StaticGenerator\Generator\MediaGenerator,
            Pushword\StaticGenerator\Generator\RobotsGenerator,
            Pushword\StaticGenerator\Generator\ErrorPageGenerator,
            Pushword\StaticGenerator\Generator\CopierGenerator,
            Pushword\StaticGenerator\Generator\CNAMEGenerator,
          ],
        assets:
          {
            javascripts: ["assets/app.min.js"],
            stylesheets: ["assets/tw.min.css"],
          },
        color_bg: "#fff",
        static_copy: ["assets"],
      }
    - {
        hosts: [admin-block-editor.test],
        base_url: "https://admin-block-editor.test",
      }
