# Used for test...
parameters:
  locale: 'en'
  database: '%env(resolve:DATABASE_URL)%'
  secret: 'myS3cretKey' #'%env(APP_SECRET)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']
